config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/" => "home#index"
  resources :todos
  resources :users
  post "/users/login", to: "users#login"

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: true

  belongs_to :user

  def self.to_displayable_list
    all.map { |todo| todo.to_displayable_string }.join("\n")
  end

  def self.overdue
    where("due_date <  ? AND completed = ?", Date.today, false)
  end

  def self.due_today
    where("due_date = ?", Date.today)
  end

  def self.due_later
    where("due_date > ?", Date.today)
  end

  def self.completed
    all.where(completed: true)
  end

  def self.show_list
    puts "My Todo-list\n\n"

    puts "Overdue\n"
    puts overdue.to_displayable_list
    puts "\n\n"

    puts "Due Today\n"
    puts due_today.to_displayable_list
    puts "\n\n"

    puts "Due Later\n"
    puts due_later.to_displayable_list
    puts "\n\n"
  end

  def self.add_task(a)
    create!(todo_text: a[:todo_text], due_date: Date.today + a[:due_in_days], completed: false)
  end

  def self.mark_as_complete(id)
    todo = find(id)
    todo.completed = true
    todo
  end

  def due_today?
    due_date == Date.today
  end

  def to_displayable_string
    display_status = completed ? "[X]" : "[ ]"
    display_date = due_today? ? nil : due_date
    "#{id} #{display_status} #{todo_text} #{display_date}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :todos
  validates :first_name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  def to_pleasant_string
    "#{id} #{name} #{email} #{password}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      # halt that request cycle
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    # @current_user_id = session[:current_user_id]
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      # render plain: "You have entered correct password"
      redirect_to "/"
    else
      # render plain: "Incorrect password"
      flash[:error] = "Your Login attempt was Invalid. Please retry"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    # render plain: Todo.order(:due_date).map { |todo| todo.to_pleasant_string }.join("\n")
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = current_user.todos.find(id)
    # render plain: todo.to_pleasant_string
    render "todo"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end

    # response_text = "Hey your new todo is created with id #{new_todo.id}"
    # render plain: response_text
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    # render plain: "Updated todo completed to #{completed}"
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in
  # skip_before_action :verify_authenticity_token

  def new
    render "new"
  end

  def index
    # render plain: User.all.map { |user| user.to_pleasant_string }.join("\n")
    render "index"
  end

  def create
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    password = params[:password]
    new_user = User.new(
      first_name: first_name,
      last_name: last_name,
      email: email,
      password: password,
    )

    if new_user.save
      flash[:msg] = "Account successfully created! Please Sign-In"
      redirect_to "/"
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to "/"
    end

    # response_text = "A new user has been created with id #{new_user.id}"
    # render plain: response_text
  end

  def login
    email = params[:email]
    password = params[:password]
    if User.find_by(email: email, password: password)
      render plain: "true"
    else
      render plain: "false"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="Home-title" > Welcome to the Todo HomePage</p>

<h3 class="Home-authenticate">
    If you are a new user <%= link_to "sign up here", new_user_path %>
</h3>

<h3 class="Home-authenticate">
    If you are an existing user <%= link_to "sign-in here", sessions_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>

    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.first_name %>!
        <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
      </p>
    <% end %>
    
    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>

       <% if flash[:msg] %>
      <p class="Flash-msg">
        <%= flash[:msg] %>
      </p>
    <% end %>
    
    <%= yield %>
      </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
    <div class="TodoSectionTitle">
      <p class="TodoSectionTitle-text"><%= section_title %></p>
      <p class="TodoSectionTitle-RemaningCount"> <%= todos.completed.count %> /<%= todos.count %></p>
    </div>
        
    <ul>
      <% todos.all.each do |todo| %>
        <li class="TodoItem">
          <div class="TodoItem-container">  
            <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
              <%= check_box_tag "completed", "isCompleted", todo.completed,
                                class: "TodoItem-checkbox", onclick: "this.form.submit()" %>

            <% end %>
              <p  class='<%= todo.completed ? "TodoItem-completedText" : "" %>'> 
                <%= todo.todo_text %>  
              </p>

              <% if show_due_date %>
                <p class="TodoItem-dueDate" ><%= todo.due_date.to_s(:short) %></p>
              <% end %>

              <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
                <a class="TodoItem-delete" href="javascript:void(0)">
                  <%= image_submit_tag "delete.png" %>
                </a>
              <% end %>
          </div>
        </li>
      <% end %>
    </ul>

</section>

app/views/todos/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Todo Manager</title>
    <link type="text/css" rel="stylesheet" href="todo-app.css" />
  </head>
  <body>
    <h1 class="TodoPage-title">My Todo-List</h1>

    <main class="TodoPageMain">
    <%= form_with(url: "/todos", method: "post", class: "AddTodo") do %>
        <%= text_field_tag "todo_text", nil, placeholder: "What's next?", class: "AddTodo-text" %>
        <%= date_field_tag "due_date", nil, class: "AddTodo-date" %>
        <%= submit_tag "Add", class: "AddTodo-button" %>

      <% end %>


    <%= render partial: "todo-section", locals: {
                 section_title: "Overdue",
                 todos: @todos.overdue,
                 show_due_date: true,
               } %>
    <%= render partial: "todo-section", locals: {
                 section_title: "Due Today",
                 todos: @todos.due_today,
                 show_due_date: false,
               } %>
    <%= render partial: "todo-section", locals: {
                 section_title: "Due Later",
                 todos: @todos.due_later,
                 show_due_date: true,
               } %>

    </main>
  </body>
</html>

app/views/todos/todo.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Todo Manager</title>
  </head>
  <body>
    <h1 class="TodoPage-title">My Todo-List</h1>


<p>This shows the list of Todos<p>

<%= Todo.to_displayable_list %>
</body>
</html>

app/views/users/index.html.erb
<p> If you are a new user sign up here</p>

app/views/users/new.html.erb
<p class="NewUsers-title">Welcome new User</p>

<section class="UsersNew">

<%= form_with url: users_path do |form| %>

    <div class="Form-section">  
        <p class="FormInput-label">First Name <span>*</span> </p>
        
        <%= form.text_field :first_name, class: "Form-Input" %>
    </div>
  
    <div class="Form-section">  
        <p class="FormInput-label">Last Name</p>
        <%= form.text_field :last_name, class: "Form-Input" %>
    </div>
   
    <div class="Form-section">  
        <p class="FormInput-label">Email <span>*</span></p>
        <%= form.email_field :email, class: "Form-Input" %>
    </div>
   
    <div class="Form-section">  
        <p class="FormInput-label">Password <span>*</span></p>
        <%= form.password_field :password, class: "Form-Input" %>
    </div>
    <div class="Form-section">
        <%= form.submit "Sign-up", class: "Form-submit" %>
    </div>
<% end %>

</section>